#!/bin/bash

echo "Create folder for the startup script..."
mkdir -p ~/.ipython/profile_default/startup
echo "Done..."

echo "Copy the startup script..."
cp binder/00-init-python-env.ipy ~/.ipython/profile_default/startup
echo "Done..."
